[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/privacy"
  to = "https://docs.ridealert.co/privacy-policy"
  status = 301

[[redirects]]
  from = "/terms"
  to = "https://docs.ridealert.co/terms-of-use"
  status = 301

[[redirects]]
  from = "/faq"
  to = "https://docs.ridealert.co/faq"
  status = 301

[[headers]]
  for = "/images/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"